### ISSUE TITLE
fcFolder in combination with symlinks

### ISSUE THREAD

**Issue by Dexnero** [grefel/chainGREP#2]
macOS bug, line 234: 

`fcFolder = File(app.scriptPreferences.scriptsFolder.parent.parent + "/Find-Change Queries/" + folderType);
` 

It throws an error if scriptsFolder is a symlink, then .parent.parent looks in the parent directories where the symlink points to and no longer in the Library folder where the Scripts folder usually is.

**Comment by grefel** [comment]
I dont't think there is a clean solution for this, as you changed your InDesign configuration. The script needs the proper location of the InDesign user settings respectively the folder with the GREP-Queries. 
I would recomend putting symlinks in the _Scripts Folder_ not changing the _Scripts Folder_ to a symlink.

**Comment by Dexnero** [comment]
You're absolutly right, didn't thought of that – I was a bit eager with my symlink :)
Thanks :)
